sysutils/qmk_hid: Init at 0.1.12
Build fails with:
``
===>   Updating Cargo.lock
error: no matching package named `clap` found
location searched: registry `crates-io`
required by package `qmk_hid v0.1.12 (/home/zoid/freebsd-ports/sysutils/qmk_hid/work/qmk_hid-0.1.12)
```

Signed-off-by: Daniel Schaefer <dhs@frame.work>